const address = [
{ name: '北京', value: 1 },
{ name: '上海', value: 2 },
{ name: '天津', value: 3 },
{ name: '重庆', value: 4 },
{ name: '河北', value: 5 },
{ name: '山西', value: 6 },
{ name: '辽宁', value: 7 },
{ name: '吉林', value: 8 },
{ name: '黑龙江', value: 9 },
{ name: '江苏', value: 10 },
{ name: '浙江', value: 11 },
{ name: '安徽', value: 12 },
{ name: '福建', value: 13 },
{ name: '江西', value: 14 },
{ name: '山东', value: 15 },
{ name: '河南', value: 16 },
{ name: '湖北', value: 17 },
{ name: '湖南', value: 18 },
{ name: '广东', value: 19 },
{ name: '海南', value: 20 },
{ name: '四川', value: 21 },
{ name: '贵州', value: 22 },
{ name: '云南', value: 23 },
{ name: '陕西', value: 24 },
{ name: '甘肃', value: 25 },
{ name: '青海', value: 26 },
{ name: '台湾', value: 27 },
{ name: '西藏', value: 28 },
{ name: '广西', value: 29 },
{ name: '内蒙古', value: 30 },
{ name: '宁夏', value: 31 },
{ name: '新疆', value: 32 },
{ name: '香港', value: 33 },
{ name: '澳门', value: 34 }
]

module.exports = address;